strategy:
  matrix:
    # linux:
    #   imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    # windows:
    #   imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
# Linux
# - bash: |
#     export IPADDR=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
#     echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
#   condition: eq( variables['Agent.OS'], 'Linux' )
#   displayName: Get IP on Linux
# macOS
- bash: |
    brew update
    brew install ykpers libyubikey libusb swig openssl
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Install deps on macOS
# Windows
# - powershell: |
#     Set-Variable -Name IPADDR -Value ((Get-NetIPAddress | ?{ $_.AddressFamily -eq "IPv4" -and !($_.IPAddress -match "169") -and !($_.IPaddress -match "127") } | Select-Object -First 1).IPAddress)
#     Write-Host "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
#   condition: eq( variables['Agent.OS'], 'Windows_NT' )
#   displayName: Get IP on Windows

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: pip install .
  displayName: 'Install yubikey-manager'
