strategy:
  matrix:
    linux-ubuntu-16-04:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    # windows-64bit:
    #   imageName: 'vs2017-win2016'
    #   platform: x64
    # windows-32bit:
    #   imageName: 'vs2017-win2016'
    #   platform: x86
pool:
  vmImage: $(imageName)

steps:
# Linux
- bash: |
    sudo apt-add-repository -y ppa:yubico/stable
    sudo apt-get update
    sudo apt-get install -qq libykpers-1-1 python-pyscard swig libpcsclite-dev
    pip install --disable-pip-version-check --upgrade pip
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Install deps
# macOS
- bash: |
    brew update
    brew install ykpers libyubikey libusb swig openssl
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Install deps
# Windows
# - powershell: |
#     Set-Variable -Name IPADDR -Value ((Get-NetIPAddress | ?{ $_.AddressFamily -eq "IPv4" -and !($_.IPAddress -match "169") -and !($_.IPaddress -match "127") } | Select-Object -First 1).IPAddress)
#     Write-Host "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
#   condition: eq( variables['Agent.OS'], 'Windows_NT' )
#   displayName: Get IP on Windows

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install .
  displayName: 'Install yubikey-manager'
